# Audio Configuration
audio:
  sample_rate: 16000
  channels: 1
  chunk_duration: 60 # seconds

# Model Configuration
model:
  size: "tiny"
  language: "en"
  device: 1

# Paths
paths:
  recordings: "data/recordings"
  transcripts: "data/transcripts"
